version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-dir=output/data
    outputs:
      highly_sensitive:
        cohort: output/data/input.csv

  descriptive_summary_table:
    run: r:latest analysis/descriptive_summaries.R
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        data: output/tables/table.csv
        cohort: output/descriptive.png
